# Generated by Django 3.2.4 on 2022-03-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickerno', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('mda', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=30)),
                ('engineno', models.CharField(max_length=30)),
                ('chassisno', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=30)),
                ('vehicletype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cooling_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiatorcondition', models.CharField(max_length=30)),
                ('fan', models.CharField(max_length=30)),
                ('ac', models.CharField(max_length=30)),
                ('belts', models.CharField(max_length=30)),
                ('horsepipes', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
    ]
