# Generated by Django 4.0.3 on 2022-03-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentInspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='windshield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.CharField(max_length=30)),
                ('blades', models.CharField(max_length=30)),
                ('mouldings', models.CharField(max_length=30)),
                ('wipermototrs', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorsRHF', models.CharField(max_length=30)),
                ('motorsRHR', models.CharField(max_length=30)),
                ('motorsLHF', models.CharField(max_length=30)),
                ('motorsLHR', models.CharField(max_length=30)),
                ('glasscondition', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockring', models.CharField(max_length=30)),
                ('wheelsandrims', models.CharField(max_length=30)),
                ('fasteners', models.CharField(max_length=30)),
                ('nuts', models.CharField(max_length=30)),
                ('welds', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clutchassembly', models.CharField(max_length=30)),
                ('gearbox', models.CharField(max_length=30)),
                ('propellershaft', models.CharField(max_length=30)),
                ('drivingshafts', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontRH', models.CharField(max_length=30)),
                ('frontLH', models.CharField(max_length=30)),
                ('rearRH', models.CharField(max_length=30)),
                ('rearLH', models.CharField(max_length=30)),
                ('sparetire', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubolts', models.CharField(max_length=30)),
                ('bushes', models.CharField(max_length=30)),
                ('springassembly', models.CharField(max_length=30)),
                ('tongue', models.CharField(max_length=30)),
                ('radius', models.CharField(max_length=30)),
                ('tracking', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='steering_mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steeringplay', models.CharField(max_length=30)),
                ('steeringcolumn', models.CharField(max_length=30)),
                ('frontaxlebeam', models.CharField(max_length=30)),
                ('steeringgear', models.CharField(max_length=30)),
                ('pitmanarm', models.CharField(max_length=30)),
                ('powersteering', models.CharField(max_length=30)),
                ('balljoints', models.CharField(max_length=30)),
                ('tierod', models.CharField(max_length=30)),
                ('steeringnuts', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='safe_loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedcondition', models.CharField(max_length=30)),
                ('bucketcondition', models.CharField(max_length=30)),
                ('doorhinges', models.CharField(max_length=30)),
                ('bedhingesRH', models.CharField(max_length=30)),
                ('bedhingesLH', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poor', models.CharField(max_length=30)),
                ('fair', models.CharField(max_length=30)),
                ('good', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='lights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumpLH', models.CharField(max_length=30)),
                ('lumpRH', models.CharField(max_length=30)),
                ('indicatorFLH', models.CharField(max_length=30)),
                ('indicatorRRH', models.CharField(max_length=30)),
                ('brakeRH', models.CharField(max_length=30)),
                ('reverseRH', models.CharField(max_length=30)),
                ('parkinglights', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framemembers', models.CharField(max_length=30)),
                ('wheelclearance', models.CharField(max_length=30)),
                ('axleassemblies', models.CharField(max_length=30)),
                ('vehiclebody', models.CharField(max_length=30)),
                ('bodypaints', models.CharField(max_length=30)),
                ('crossmembers', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='exhaust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemcondition', models.CharField(max_length=30)),
                ('sensorcondition', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oillevel', models.CharField(max_length=30)),
                ('visibleleaks', models.CharField(max_length=30)),
                ('generaloperation', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
        migrations.CreateModel(
            name='brakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicebrakes', models.CharField(max_length=30)),
                ('parkingbrakes', models.CharField(max_length=30)),
                ('electricbrakes', models.CharField(max_length=30)),
                ('hydraulicbrakes', models.CharField(max_length=30)),
                ('vacuum', models.CharField(max_length=30)),
                ('brakedrum', models.CharField(max_length=30)),
                ('pressurewarn', models.CharField(max_length=30)),
                ('tractorprotection', models.CharField(max_length=30)),
                ('aircompressor', models.CharField(max_length=30)),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentInspection.vinfo')),
            ],
        ),
    ]
