# Generated by Django 4.0.3 on 2022-03-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentInspection', '0002_windshield_windows_wheels_transmission_tires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brakes',
            old_name='pressurewarn',
            new_name='pressurewarning',
        ),
    ]
