# Generated by Django 4.0.3 on 2022-03-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componentInspection', '0003_rename_pressurewarn_brakes_pressurewarning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windshield',
            old_name='wipermototrs',
            new_name='wipermotors',
        ),
    ]
